
package Datos.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.13
 * Mon Nov 07 14:43:08 COT 2022
 * Generated source version: 2.0.13
 * 
 */

@XmlRootElement(name = "eliminacionResponse", namespace = "http://Datos/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eliminacionResponse", namespace = "http://Datos/")

public class EliminacionResponse {


}

