
package Datos.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.13
 * Mon Nov 07 14:43:08 COT 2022
 * Generated source version: 2.0.13
 * 
 */

@XmlRootElement(name = "eliminacion", namespace = "http://Datos/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eliminacion", namespace = "http://Datos/")

public class Eliminacion {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }
    
    public void setArg0( int newArg0 ) {
        this.arg0 = newArg0;
    }
    
}

